name: Release latest

on:
  push:
    branches: ["master"]

jobs:
  # Push to latest
  cel-rule-ui-container-push-latest:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: cel-rule-ui
      registry_org: Vincent056
      tag: latest
      dockerfile_path: Dockerfile
      vendor: "CEL Rule UI Authors"
      platforms: "linux/amd64"
